# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #

# wallust-colors
#include kitty-colors.conf 

# font_family FantasqueSansM Nerd Font Mono Bold 
font_family JetBrainsMono Nerd Font Mono
font_size 13.0
bold_font auto
italic_font auto
bold_italic_font auto

enable_ligatures yes
disable_ligatures never
text_composition_strategy platform

modify_font cell_height 5px
background_opacity 0.5
# background_opacity 0.9
# background_opacity 1
confirm_os_window_close 0

# change to x11 or wayland or leave auto
linux_display_server auto

scrollback_lines 2000
wheel_scroll_min_lines 1

enable_audio_bell no

window_padding_width 10

enabled_layouts tall:bias=50;full_size=1;mirrored=false

map ctrl+alt+[ layout_action decrease_num_full_size_windows
map ctrl+alt+] layout_action increase_num_full_size_windows

tab_bar_edge top
tab_bar_style fade

# include catppuccin.conf
# include kitty-colors.conf

# vim:ft=kitty

## name: Kanagawa
## author: Tommaso Laurenzi
## license: MIT
## upstream: https://github.com/rebelot/kanagawa.nvim/
## blurb: NeoVim dark colorscheme inspired by the colors of the famous painting
## by Katsushika Hokusai.

#: The basic colors

foreground                      #c5c9c5
background                      #000000
selection_foreground            #7fb4ca
selection_background            #2d4f67

#: Cursor colors

cursor                          #7fb4ca

#: URL underline color when overing with mouse

url_color                       #7aa89f

#: Tab bar colors

active_tab_foreground           #7fb4ca
active_tab_background           #1f1f28
inactive_tab_foreground         #727169
inactive_tab_background         #181616

#: The basic 16 colors

#: black
color0  #090618
color8  #727169

#: red
color1  #e46876
color9  #e82424

#: green
color2  #8a9a7b
color10 #98bb6c

#: yellow
color3  #E6C384
color11 #ffe5b6

#: blue
color4  #7e9cd8
color12 #7fb4ca

#: magenta
color5  #a292a3
color13 #938aa9

#: cyan
color6  #6a9589
color14 #7aa89f

#: white
color7  #feffff
color15 #dcd7ba


#: You can set the remaining 240 colors as color16 to color255.

color16 #c4b28a
color17 #ff5d62
