# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #CECDC9
background         #1C1D1C
cursor             #737572

active_tab_foreground     #1C1D1C
active_tab_background     #CECDC9
inactive_tab_foreground   #CECDC9
inactive_tab_background   #1C1D1C

active_border_color   #CECDC9
inactive_border_color #1C1D1C
bell_border_color     #121615

color0      #424343
color1		#121615
color2		#121615
color3		#141816
color4		#171A18
color5		#45453D
color6		#56544B
color7		#B1AFA9
color8		#7C7A76
color9		#191E1C
color10		#191E1C
color11		#1A201D
color12		#1E2320
color13		#5C5B52
color14		#737064
color15		#B1AFA9
