# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1C1D1C)
$foreground = rgb(CECDC9)
$color0 = rgb(424343)
$color1 = rgb(121615)
$color2 = rgb(121615)
$color3 = rgb(141816)
$color4 = rgb(171A18)
$color5 = rgb(45453D)
$color6 = rgb(56544B)
$color7 = rgb(B1AFA9)
$color8 = rgb(7C7A76)
$color9 = rgb(191E1C)
$color10 = rgb(191E1C)
$color11 = rgb(1A201D)
$color12 = rgb(1E2320)
$color13 = rgb(5C5B52)
$color14 = rgb(737064)
$color15 = rgb(B1AFA9)
