# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #

# animations {
#   enabled = yes
#
#   bezier = wind, 0.05, 0.9, 0.1, 1.05
#   bezier = winIn, 0.1, 1.1, 0.1, 1.1
#   bezier = winOut, 0.3, -0.3, 0, 1
#   bezier = liner, 1, 1, 1, 1
#   bezier = overshot, 0.05, 0.9, 0.1, 1.05
#   bezier = smoothOut, 0.5, 0, 0.99, 0.99
#   bezier = smoothIn, 0.5, -0.5, 0.68, 1.5
#
#   animation = windows, 1, 6, wind, slide
#   animation = windowsIn, 1, 5, winIn, slide
#   animation = windowsOut, 1, 3, smoothOut, slide
#   animation = windowsMove, 1, 5, wind, slide
#   animation = border, 1, 1, liner
# #  animation = borderangle, 1, 180, liner, loop #used by rainbow borders and rotating colors
#   animation = fade, 1, 3, smoothOut
#   animation = workspaces, 1, 5, overshot
#
#   # animations for -git or version >0.42.0
#   animation = workspacesIn, 1, 5, winIn, slide
#   animation = workspacesOut, 1, 5, winOut, slide
# }

animations {
  enabled = yes

  bezier = liner, 2, 2, 2, 2
  bezier = winIn, 0.1, 1.1, 0.1, 1.1
  bezier = winOut, 0.3, -0.3, 0, 1
  
  bezier = wind, 0.05, 0.9, 0.1, 1.05
  bezier = overshot, 0.05, 0.9, 0.1, 1.05
  bezier = smoothOut, 0.36, 0, 0.66, -0.56
  bezier = smoothIn, 0.25, 1, 0.5, 1

  animation = windows, 1, 3, overshot, slide
  animation = windowsOut, 1, 3, smoothOut, slide
  animation = windowsMove, 1, 3, default
  animation = border, 1, 3, default
  animation = fade, 1, 3, smoothIn
  animation = fadeDim, 1, 3, smoothIn
  animation = workspaces, 1, 3, default
  #animation = workspaces, 1, 3, wind

  
  # animations for -git or version >0.42.0
   animation = workspacesIn, 1, 3, wind, slide
  # animation = workspacesOut, 1, 3, winOut, slide

  # --------------
  # animation = border, 1, 1, liner
  # animation = borderangle, 1, 180, liner, loop #used by rainbow borders and rotating colors
  animation = borderangle, 1, 30, liner, loop
  # animation= specialWorkspace, 1, 2, overshot, slidefadevert
  animation= specialWorkspace, 1, 2.3, overshot, slide 
}

